### PR TITLE
add optional headers to all fetch calls

### PR DESCRIPTION
**Pull request by kpotter-m2**
had a need to add custom headers to pass an authentication token to our ollama proxy server

please take a look and edit as you all see fit

### CODE REVIEW

**Comment by kpotter-m2** [comment]
@BruceMacD please review at your earliest convenience

**Comment by kpotter-m2** [comment]
@BruceMacD

**Comment by kpotter-m2** [comment]
@BruceMacD or @jmorganca, this is ready for review

**Comment by BruceMacD** [comment]
Hi @kpotter-m2, sorry for the delayed response. This is looking good.

I am wondering if the headers you are sending are constant (like an API key)? If that is the case it may be easier to just set the headers on the Ollama client object rather than passing them in with every request.

```javascript
export class Ollama {
  protected readonly config: Config
  protected readonly fetch: Fetch
  protected readonly headers: Headers
  private abortController: AbortController
```

**Comment by GridexX** [comment]
Hello @BruceMacD !

I'm really interested about this feature. I need a global API key, that could be passed as a constant, like you said. Would be great to be added !

**Comment by kpotter-m2** [comment]
thanks @BruceMacD! I think that's spot on - will take a look over the next week hopefully to address that improvement

**Comment by ronneldavis** [comment]
@kpotter-m2 is this something you're still working on? Would be happy to contribute if you are not

**Comment by kpotter-m2** [comment]
> @kpotter-m2 is this something you're still working on? Would be happy to contribute if you are not

please pick up where I left off, haven't had time to resume this work. apologies & thank you!

**Comment by kpotter-m2** [comment]
closing in favor of using https://github.com/ollama/ollama-js/pull/138 instead, nice work

**Pull request closed without merging**
