### PR TITLE
fix: use more compatible ReadableStream iteration method

### PR DESCRIPTION
**Pull request by nshcr**
Related issue #13.

### CODE REVIEW

**Comment by bm777** [comment]
@nshcr are you able to stream with this patch?

**Comment by nshcr** [comment]
> @nshcr are you able to stream with this patch?

Certainly, I tested it by import into a Vite project, and it successfully streams text in the latest browsers (Chromium, Firefox, Safari) as well as in Node.js (v18.18), with the `stream` option is set to true.

**Comment by bm777** [comment]
Ok. I'm going to try it. I'm using it in an electron app, a chromium tab.

**Review by bm777 — COMMENTED** [review]
It works in Electron.

**Review by BruceMacD — APPROVED** [review]
Thanks for fixing this, looks good

**Comment by jmorganca** [comment]
Does this fix https://github.com/ollama/ollama-js/issues/33 ?

**Comment by BruceMacD** [comment]
I think #33 could be from the file reading logic (which wont work in a browser at the moment)

**Pull request merged**
