### PR TITLE
AbortableAsyncIterator

### PR DESCRIPTION
**Pull request by hopperelec**
Closes https://github.com/ollama/ollama-js/issues/95

### CODE REVIEW

**Comment by HopperElec** [comment]
I've just realised https://github.com/ollama/ollama-js/tree/main/examples/abort exists, I'll update this example shortly. I've also just realised that it's probably a good idea to still have a function to abort all requests but, since each request now has it's own AbortController, this will need to be implemented differently to before

**Comment by HopperElec** [comment]
This probably isn't the best way to do this, and it might be useful to allow users to interact with the array of requests in more ways, but I wanted to keep it simple so I can respond to feedback more easily

**Review by BruceMacD — COMMENTED** [review]
Sorry for the slow response this is looking good to me. Being able to abort the returned stream is definitely the correct behaviour. Was there anything else you were looking to add to this?

**Comment by HopperElec** [comment]
No worries! There's definitely other things which could be added, such as some extra error handling and allowing users to interact with the array of streamed requests (but while maintaining encapsulation), but I also want to avoid over-complicating it. If anyone thinks these should be added, I'm happy to include them, but otherwise I'm happy with it as it is.

**Review by BruceMacD — APPROVED** [review]
Thanks for the contribution, merging now to test for the next release.

**Comment by mattbasta** [comment]
Hey @hopperelec and @BruceMacD, I'm a bit late to the convo, but I wanted to raise a concern in the examples. See: https://github.com/ollama/ollama-js/blob/main/examples/abort/any-request.ts#L10

Because `.generate()` (or the promise created by calling `.then()`) isn't being `await`ed, the `catch` won't catch the abort error, making the `try` effectively a no-op. You might consider putting the `catch` block's contents into a `.catch()` chained onto the `.then()`.

**Comment by hopperelec** [comment]
Good catch! I'll be busy for the rest of today, but I might be able to fix this tomorrow. If someone else sees this today, feel free to beat me to it!

**Pull request merged**
